CREATE TABLE scientist ( 
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    lastname CHAR(64) NOT NULL, firstname CHAR(64) NOT NULL, 
    patronymic CHAR(64), 
    datebirdth DATE NOT NULL, 
    gender CHAR(64) NOT NULL, 
    nationality CHAR(64), 
    academicdegree CHAR(64), 
    position CHAR(128), 
    address CHAR(256), 
    phone CHAR(13)
);

INSERT INTO scientist
    VALUES (DEFAULT, 'Петров', 'Aндрей', 'Александрович', '07/08/1999', 1,
            'белорус', 'доктор наук', 'директор отдела научных исследований',
            '220000, г.Минск, ул.Грибоедова, 25-21', '+375257705629'),
           (DEFAULT, 'Абилова', 'Эвелина', 'Эльчиновна', '04/10/2002', 2,
            'талышка', 'доктор наук', 'директор отдела технических исследований',
            '220000, г.Минск, ул.В.Пупкина, 5-11', '+375334531217'),
           (DEFAULT, 'Иванов', 'Василий', 'Пупкинович', '10/02/1988', 1,
            'белорус', 'доктор наук', 'доцент отдела уфологических исследований',
            '220000, г.Минск, ул.В.Пупкина, 5-12', '+375294531822'),
           (DEFAULT, 'Калыш', 'Елизавета', 'Абрагимовна', '12/15/1998', 2,
            'белоруска', 'кандидат технических наук', 'Зам директора отдела технических исследований',
            '220000, г.Минск, ул.В.Ленина, 3-17', '+375294653444'),
           (DEFAULT, 'Эрбарго', 'Джой', 'Васильевич', '10/02/1996', 1,
            'белорус', 'кандидат технических наук', 'доцент отдела технических исследований',
            '220000, г.Минск, ул.В.Пупкина, 5-12', '+375294531822');

CREATE TABLE organization (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_name CHAR(256) NOT NULL,
    org_description CHAR(256)
);

INSERT INTO organization
    VALUES (DEFAULT, 'Академия наук Республики Беларусь', NULL),
           (DEFAULT, 'Белорусский государственный университет', NULL);

ALTER TABLE scientist ADD organization_id INTEGER REFERENCES organization (id);

UPDATE scientist SET organization_id = 1 WHERE id = 1;

UPDATE scientist SET organization_id = 2 WHERE id = 2;

UPDATE scientist SET organization_id = 2 WHERE id = 3;

UPDATE scientist SET organization_id = 2 WHERE id = 4;

UPDATE scientist SET organization_id = 1 WHERE id = 5;